### ISSUE TITLE
Client not working with v2.2.0

### ISSUE THREAD

**Issue by laxas** [jlowin/fastmcp#193]
I have a simple client demo:

```python
from fastmcp import Client
import asyncio

async def main():
    async with Client("mcp_server.py") as client:
        tools = await client.list_tools()
        print(f"Available tools: {tools}")

asyncio.run(main())
```

That works as expectet with Version 2.1.2 but returns the follwoing error with version 2.2.0:

```
...
mcp.shared.exceptions.McpError: 'FastMCP' object has no attribute 'get_tools'
```

**Comment by MarshallEriksen-Neura** [comment]
![Image](https://github.com/user-attachments/assets/320ab114-2d46-46fd-890a-c9b6361379d6)

**Comment by jlowin** [comment]
Unfortunately 2.2 included a small set of breaking changes that may make it difficult to run in-process servers in the way you're attempting to do if the client in one file is 2.2 and the server in the other is 2.1. I will try to smooth over those frictions where possible.
